---
- name: Verify
  hosts: molecule
  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Verify Anubis is installed
      ansible.builtin.assert:
        that: "'anubis' in ansible_facts.packages"
        fail_msg: "anubis package is not installed"

    - name: Check telemetry endpoint
      ansible.builtin.uri:
        url: "http://{{ ansible_host }}:9090/metrics"
        method: GET
        status_code: 200
