---
molecule:
  hosts:
    deb12-primary:
    deb12-replica:
    deb13-primary:
    deb13-replica:

deb12:
  hosts:
    deb12-primary:
    deb12-replica:

deb13:
  hosts:
    deb13-primary:
    deb13-replica:

postgresql:
  hosts:
    deb12-primary:
    deb12-replica:
    deb13-primary:
    deb13-replica:

replica:
  hosts:
    deb12-replica:
      postgresql_primary_host: deb12-primary
    deb13-replica:
      postgresql_primary_host: deb13-primary
