---
- name: Prepare
  hosts: localhost

  vars:
    tmpdir: /tmp/molecule

  tasks:
    - name: Create tmpdir
      ansible.builtin.file:
        path: "{{ tmpdir }}"
        state: directory
        mode: "0755"

    - name: Generate CA key
      ansible.builtin.command:
        cmd: >-
          openssl ecparam -name secp384r1 -genkey -noout -out ca.key
        chdir: "{{ tmpdir }}"
        creates: "{{ tmpdir }}/ca.key"

    - name: Generate CA cert
      ansible.builtin.command:
        cmd: >-
          openssl req -x509 -new -nodes -key ca.key -sha256 -days 1 -out ca.crt -subj "/C=BE/ST=Brussels Capital/L=Brussels/O=Hachyderm/OU=pgBackRest/CN=CI CA"
        chdir: "{{ tmpdir }}"
        creates: "{{ tmpdir }}/ca.crt"

    - name: Generate server keys
      ansible.builtin.command:
        cmd: >-
          openssl ecparam -name prime256v1 -genkey -noout -out {{ server }}.key
        chdir: "{{ tmpdir }}"
        creates: "{{ tmpdir }}/{{ server }}.key"
      loop: "{{ groups['molecule'] }}"
      loop_control:
        loop_var: server

    - name: Generate server CSRs
      ansible.builtin.command:
        cmd: >-
          openssl req -new -nodes -out {{ server }}.csr -key {{ server }}.key -subj "/CN={{ server }}"
        chdir: "{{ tmpdir }}"
        creates: "{{ tmpdir }}/{{ server }}.csr"
      loop: "{{ groups['molecule'] }}"
      loop_control:
        loop_var: server

    - name: Generate server certificates
      ansible.builtin.command:
        cmd: >-
          openssl x509 -req -in {{ server }}.csr -days 1 -CA ca.crt -CAkey ca.key -CAcreateserial -out {{ server }}.crt
        chdir: "{{ tmpdir }}"
        creates: "{{ tmpdir }}/{{ server }}.crt"
      loop: "{{ groups['molecule'] }}"
      loop_control:
        loop_var: server


- name: Copy certificates
  hosts: molecule
  become: true

  vars:
    tmpdir: /tmp/molecule

  tasks:
    - name: Create TLS group
      ansible.builtin.group:
        name: tls

    - name: Create TLS directory
      ansible.builtin.file:
        path: /etc/tls
        state: directory
        owner: root
        group: tls
        mode: "0755"

    - name: Copy CA cert
      ansible.builtin.copy:
        src: "{{ tmpdir }}/ca.crt"
        dest: /etc/tls/ca.crt
        owner: root
        group: tls
        mode: "0644"

    - name: Copy certs
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: tls
        mode: "{{ item.mode }}"
      loop:
        - src: "{{ tmpdir }}/{{ inventory_hostname }}.crt"
          dest: /etc/tls/server.crt
          mode: "0644"
        - src: "{{ tmpdir }}/{{ inventory_hostname }}.key"
          dest: /etc/tls/server.key
          mode: "0640"
