---
molecule:
  hosts:
    deb12-primary:
    deb12-replica:
    deb13-primary:
    deb13-replica:

primary:
  hosts:
    deb12-primary:
    deb13-primary:

replica:
  hosts:
    deb12-replica:
    deb13-replica:

deb12:
  hosts:
    deb12-primary:
    deb12-replica:

deb13:
  hosts:
    deb13-primary:
    deb13-replica:
