---
- name: Generate certificates
  hosts: localhost

  vars:
    tmpdir: /tmp/molecule

  tasks:
    - name: Create tmpdir
      ansible.builtin.file:
        path: "{{ tmpdir }}"
        state: directory
        mode: "0755"

    - name: Install faketime
      become: true
      ansible.builtin.package:
        name: faketime
      when: expired | default(false) | bool

    - name: Generate CA key
      ansible.builtin.command:
        cmd: >-
          openssl ecparam -name secp384r1 -genkey -noout -out ca.key
        chdir: "{{ tmpdir }}"
        creates: "{{ tmpdir }}/ca.key"

    - name: Generate CA cert
      ansible.builtin.command:
        cmd: >-
          {% if expired | default(false) | bool %}faketime '2 days ago'{% endif %}
          openssl req -x509 -new -nodes -key ca.key -sha256 -days 1 -out ca.crt -subj "/C=BE/ST=Brussels Capital/L=Brussels/O=Hachyderm/OU=pgBackRest/CN=CI CA"
        chdir: "{{ tmpdir }}"
        creates: "{{ tmpdir }}/ca.crt"

    - name: Generate server keys
      ansible.builtin.command:
        cmd: >-
          openssl ecparam -name prime256v1 -genkey -noout -out {{ server }}.key
        chdir: "{{ tmpdir }}"
        creates: "{{ tmpdir }}/{{ server }}.key"
      loop: "{{ groups['molecule'] }}"
      loop_control:
        loop_var: server

    - name: Generate server CSRs
      ansible.builtin.command:
        cmd: >-
          openssl req -new -nodes -out {{ server }}.csr -key {{ server }}.key -subj "/CN={{ server }}"
        chdir: "{{ tmpdir }}"
        creates: "{{ tmpdir }}/{{ server }}.csr"
      loop: "{{ groups['molecule'] }}"
      loop_control:
        loop_var: server

    - name: Generate server certificates
      ansible.builtin.command:
        cmd: >-
          {% if expired | default(false) | bool %}faketime '2 days ago'{% endif %}
          openssl x509 -req -in {{ server }}.csr -days 1 -CA ca.crt -CAkey ca.key -CAcreateserial -out {{ server }}.crt
        chdir: "{{ tmpdir }}"
        creates: "{{ tmpdir }}/{{ server }}.crt"
      loop: "{{ groups['molecule'] }}"
      loop_control:
        loop_var: server
